export const ROUTES = {
  HOME: '/',
  LOGIN: 'login',
  REGISTER: 'register',
  GAMES: 'games',
  BROWSER: 'browser',
  LIBRARY: 'library',
  FILTERS: 'filters',
  GAME_ID: 'game/:id',
  GAMES_CATEGORY: 'games/:category',
  GAMES_CATEGORY_GAMEID: 'games/:category/game/:id',
  BROWSER_CATEGORY: 'browser/:category',
  BROWSER_CATEGORY_GAMEID: 'browser/:category/game/:id',
  NOT_FOUND: '*',
}
